import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const tokens = JSON.parse(
  await readFile(join(root, 'design-tokens.json'), 'utf8'),
)
const entries = Object.entries(tokens).sort(([left], [right]) =>
  left.localeCompare(right),
)
const output = [
  '/* Generated by scripts/generate-tokens.mjs. */',
  ':root {',
  ...entries.map(([name, value]) => `  --${name}: ${value};`),
  '}',
  '',
].join('\n')

const outputDirectory = join(root, 'src', 'styles')
await mkdir(outputDirectory, { recursive: true })
await writeFile(join(outputDirectory, 'tokens.css'), output)
